### ISSUE TITLE
Simplify calculating PageWrapper components size and placement based on Navbar

### ISSUE THREAD

**Issue by WinstonHall** [Two-Boys-and-a-Dream/vg-web#32]
Navbars width is always one hard value, 250px,  so we should be using the calc function inside a css file, or using components style prop like in the example image below.

![Image](https://user-images.githubusercontent.com/98111187/212281183-291f4488-a78e-46e9-b060-a8bb02358734.png)

We would no longer need size.js, unless there is something I haven't seen using it.

**Comment by Raymond-Cox** [comment]
I think this should all be moved towards scss. We can store these as variables in a "global-like" scss file, and then import into others and use.
