### ISSUE TITLE
Parcel question

### ISSUE THREAD

**Issue by ghost** [Two-Boys-and-a-Dream/vg-web#34]
Unsure what to think about this, and doing other work right now. Just wondering if this raises any concern?

![Image](https://user-images.githubusercontent.com/98111187/212283970-1453333a-9b07-4980-b55a-b5bb6f7094ab.png)
(Screenshot of web-browser console log)

**Comment by Raymond-Cox** [comment]
I've been keeping an eye on this thread https://github.com/parcel-bundler/parcel/issues/6685

If we continue to experience this after we remove Chakra, I'll investigate.

**Comment by Raymond-Cox** [comment]
@WinstonHall Now that Chakra is gone from the codebase, report any further issues you experience that you believe may be related to Parcel here.
