### ISSUE TITLE
Add logic to filter duplicate articles

### ISSUE THREAD

**Issue by ghost** [Two-Boys-and-a-Dream/vg-web#36]
Example screen shots from deployed page. Not all articles repeat, most of them are. At this current time of taking screen shots, only the first and last article do not repeat. Maybe its because the repeating article for the first one is 1 index out of the range and the last article might be one off as well, assuming we get a set number of articles they might be repeating as well.

![Image](https://user-images.githubusercontent.com/98111187/212310643-39f700d6-767e-442f-bb65-6013c15350b6.png)

![Image](https://user-images.githubusercontent.com/98111187/212310271-a89353e6-44bf-4e0a-a354-def9e3bfec04.png)

![Image](https://user-images.githubusercontent.com/98111187/212310855-1a3fb51b-0406-4cbd-b85c-515eaebd3cb4.png)

Examples of articles that only show up once.

Just the first article in this image doesn't repeat, the one with the car bg-image repeats.

![Image](https://user-images.githubusercontent.com/98111187/212311068-8e4f0894-cccc-4d75-96ef-2ee84846dc13.png)

Just the last article in this image doesn't repeat.

![Image](https://user-images.githubusercontent.com/98111187/212311350-0c1ece4e-3c4a-4fb3-a659-8bfd9777aaaf.png)

**Comment by WinstonHall** [comment]
Looking more into it, @Raymond-Cox might have already fixed it, but gh-page might not be pushed up to that point.

**Comment by Raymond-Cox** [comment]
This is a good find. Our news caching happens every hour, grabbing the 10 most recent gaming articles. During the day, new articles are constantly posted. At night, that is highly unlikely. The most noticeable time to see duplications would be during the evening. Ideally the API should check for uniques before storing articles. I think it also wouldn't hurt for the Front-End to create a unique set (filter out dupes), in case the BE fails.

**Comment by Raymond-Cox** [comment]
This issue is now about adding logic to the FE web code to remove duplicate news article objects from the array before mapping/rendering.
