### ISSUE TITLE
New Design - GameCard

### ISSUE THREAD

**Issue by WinstonHall** [Two-Boys-and-a-Dream/vg-web#46]
Updated the <GameCard /> Component to match new design. 
https://www.figma.com/file/2Yvkp0qplQuXggYBnadf9m/Untitled?node-id=0%3A1

![Desktop - 4](https://user-images.githubusercontent.com/33842042/212762240-7a94cf1d-111f-4b9d-9594-a273154e3e4b.png)

**Comment by Raymond-Cox** [comment]
@mayashley This Home page redesign is now in flight.

@WinstonHall Please provide screenshots of the UI and request a review from Ashley when opening the PR.

**Comment by WinstonHall** [comment]
Leaving notes, I dont know where else to put, here as I run into stuff doing this.


First note, GameCard was running into issues importing memo from react if a child component also used it.
I was lifting up one of the memos because its going to be used twice in Child Components. 
The other memo was to round any number values given to Rating, to clean up the value for a whole number string.

Is there a reason for that or is that just a weird bug?

@Raymond-Cox

**Comment by Raymond-Cox** [comment]
> First note, GameCard was running into issues importing memo from react if a child component also used it.

Weird, but ok. I've never seen such an error before.

> The other memo was to round any number values given to Rating, to clean up the value for a whole number string.

The `useMemo` in that context wasn't required, it was just an optimization. The function used to round/clean up the rating value is still necessary.
